

POSTGRESQL_USERNAME: root
POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
POSTGRESQL_HOST: ${POSTGRESQL_HOST}
POSTGRESQL_PORT: ${POSTGRESQL_PORT}
MYSQL_DATABASE: ecommerce_portfolio

#Server config
CONTAINER_PORT: ${PORT}
ACTIVE_PROFILE: dev

#Email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: marckenlygbeau@gmail.com
EMAIL_PASSWORD: cxmjrheikeieobqv
VERIFY_EMAIL_HOST: http://localhost:8000

JWT_EXPIRATION: 432_000_000
JWT_SECRET: ${SECRET}